### ISSUE TITLE
doesn't  work and multiple people have tried

### ISSUE THREAD

**Issue by Pickymarker** [AggelosAst/vencord-StatusSpoof#2]

**Comment by AggelosAst** [comment]
**Discord Android**:

When the plugin is enabled throughout the settings and you have picked any status. For instance, try picking discord android. After picking discord android and `Save & Close`, hit `CTRL + R` and your specified platform should be set to discord mobile. That can be visible `ONLY if your status is set to online` and can always be shown by people using the [PlatformIndicators](https://github.com/Vendicated/Vencord/tree/main/src/plugins/platformIndicators) plugin. It takes a while for it to show on there. Reminder, for people who dont use the platformindicators plugin, it will **NOT** show if your status is set to anything other than `Online`.
![image](https://github.com/AggelosAst/vencord-StatusSpoof/assets/87412823/84a7e087-7375-4971-a5c8-847bca8b9622)


**Console**

When the plugin is enabled throughout the settings and you have picked any status. For instance, try picking Console. After picking Console and `Save & Close`,  hit `CTRL + R` and your specified platform should be set to Console. No person can see that youre on a console but just that youre `Online` if they dont use the plugin i mentioned above. If they use the plugin, they will see a different icon next to your username.

**Comment by AggelosAst** [comment]
And to add to that, have you tried debugging the plugin the dev console? Maybe it has any error. Make sure that you can find this message in your `Developer Console` Output.
![image](https://github.com/AggelosAst/vencord-StatusSpoof/assets/87412823/2378f5bc-6d9d-4faa-9ced-48333388001a)

**Comment by Pickymarker** [comment]
I tried platform indicators and also what I meant by other people is that they tried the plugin and it didn't work

**Comment by AggelosAst** [comment]
i dont exactly understand "its not working" did you try both idnications and did they change? Or did they not. When you picked the discord android option, when you refreshed did it show you on mobile when using online status or did the platform indicators show youre on mobile. If you want more assistance, shoot me a message and we can work this out together.

**Comment by Pickymarker** [comment]
no platform indicator or anything is showing mobile and the debug stuff I sent you before

**Comment by AggelosAst** [comment]
So like, when you set Discord android option in the plugin settings and then save and then reload your discord and having the `Online` statuc as seen here doesn show you this?
![image](https://github.com/AggelosAst/vencord-StatusSpoof/assets/87412823/97d9f7c4-82d2-4aba-a73f-54a59b4e803b)
Or for the users with teh platformIndicator plugin having this?
![image](https://github.com/AggelosAst/vencord-StatusSpoof/assets/87412823/121ccfc0-7362-4a33-a44f-00bb3ba88ff1)

**Comment by Pickymarker** [comment]
the status spoof just does nothing

**Comment by AggelosAst** [comment]
So your status stays the same? Mind sharing a clip of you doing the above?

**Comment by AggelosAst** [comment]
I am working on an update by the way, i found a issue on vencord which makes it unable to work due to the encoding.

**Comment by AggelosAst** [comment]
For the upcoming update. please help me debug the plugin by showing me your output logs. If you go to `Dev Tools` > `Console` you would see messages in the format `[StatusSpoof]: text`

**Comment by AggelosAst** [comment]
Released. Recompile with the new plugin and let me know.

**Comment by AggelosAst** [comment]
Released an update. Check:

- [x] #2
- [x] https://github.com/AggelosAst/vencord-StatusSpoof/issues/2
- [x] https://github.com/AggelosAst/vencord-StatusSpoof/commit/48183cdf483b248b75afd695c4b49e1c88fcdc60
